const fs = require('node:fs');
const path = 'app/page.tsx';
let code = fs.readFileSync(path, 'utf8').replace(/\r\n/g, '\n');
const start = code.indexOf('  const commitStrokes = (next: Stroke[], previous: Stroke[]) => {');
const end = code.indexOf('  const updatePaper = (changes: Partial<PaperSettings>) => {', start);
if (start < 0 || end < 0) throw new Error('P8 ink history block not found');
const replacement = `  const commitStrokes = (next: Stroke[], previous: Stroke[]) => {\n    if (!noteInkSession.commit(activeNote.id, next, previous)) return;\n    updateActiveNote({ strokes: next });\n    setInkHistoryVersion((value) => value + 1);\n  };\n\n  const undo = () => {\n    const previous = noteInkSession.undo(activeNote.id, activeNote.strokes);\n    if (!previous) return;\n    updateActiveNote({ strokes: previous });\n    setInkHistoryVersion((value) => value + 1);\n  };\n\n  const redo = () => {\n    const next = noteInkSession.redo(activeNote.id, activeNote.strokes);\n    if (!next) return;\n    updateActiveNote({ strokes: next });\n    setInkHistoryVersion((value) => value + 1);\n  };\n\n`;
code = code.slice(0, start) + replacement + code.slice(end);
fs.writeFileSync(path, code);
console.log('P8 ink history extraction fixed');
